using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace PortalStrictLightsPatcher
{
    public class Program
    {
        private static Lazy<Settings> _settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "PortalStrictLightsPatch.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var settings = _settings.Value;
            state.PatchMod.ModHeader.Flags |= SkyrimModHeader.HeaderFlag.Small;

            var examined = 0;
            var deleted = 0;
            var alreadyPortalStrict = 0;
            var spotlightsSkipped = 0;
            var magicLightsSkipped = 0;
            var eligibleForPatching = 0;
            var patched = 0;

            foreach (var light in state.LoadOrder.PriorityOrder
                         .Light()
                         .WinningOverrides(includeDeletedRecords: true))
            {
                examined++;

                if (light.IsDeleted)
                {
                    deleted++;
                    continue;
                }

                var hasDataPortalStrict =
                    (light.Flags & Light.Flag.PortalStrict) != 0;
                var hasHeaderPortalStrict =
                    (light.MajorFlags & Light.MajorFlag.PortalStrict) != 0;

                if (hasDataPortalStrict && hasHeaderPortalStrict)
                {
                    alreadyPortalStrict++;
                    continue;
                }

                var isSpotlight =
                    (light.Flags & (Light.Flag.SpotLight | Light.Flag.ShadowSpotlight)) != 0;

                if (!settings.IncludeSpotlights && isSpotlight)
                {
                    spotlightsSkipped++;
                    continue;
                }

                var isMagicLight = light.EditorID?.Contains(
                    "magic",
                    StringComparison.OrdinalIgnoreCase) == true;

                if (!settings.IncludeMagicLights && isMagicLight)
                {
                    magicLightsSkipped++;
                    continue;
                }

                eligibleForPatching++;

                try
                {
                    var overrideRecord = state.PatchMod.Lights.GetOrAddAsOverride(light);
                    overrideRecord.Flags |= Light.Flag.PortalStrict;
                    overrideRecord.MajorFlags |= Light.MajorFlag.PortalStrict;

                    var dataFlagWritten =
                        (overrideRecord.Flags & Light.Flag.PortalStrict) != 0;
                    var headerFlagWritten =
                        (overrideRecord.MajorFlags & Light.MajorFlag.PortalStrict) != 0;

                    if (!dataFlagWritten || !headerFlagWritten)
                    {
                        throw new InvalidOperationException(
                            "Mutagen did not retain both Portal-strict flags on the override.");
                    }

                    patched++;
                }
                catch (Exception exception)
                {
                    throw new InvalidOperationException(
                        $"Failed to patch LIGH {light.FormKey} ({light.EditorID ?? "<no EditorID>"}).",
                        exception);
                }
            }

            Console.WriteLine($"""
                Portal Strict Lights classification summary
                IncludeSpotlights: {settings.IncludeSpotlights}
                IncludeMagicLights: {settings.IncludeMagicLights}
                Winning LIGH records examined: {examined}
                Deleted: {deleted}
                Already Portal-strict: {alreadyPortalStrict}
                Spotlights skipped: {spotlightsSkipped}
                Magic lights skipped: {magicLightsSkipped}
                Eligible for patching: {eligibleForPatching}
                Patched: {patched}
                """);
        }
    }
}
